# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 04:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grumblr', '0011_auto_20161004_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='follower',
            field=models.ManyToManyField(related_name='_profile_follower_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
