# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 00:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0012_profile_follower'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='token',
            field=models.CharField(default='', max_length=200),
        ),
    ]
